export const UPDATE_FRINEDS = "UPDATE_FRINEDS";

export const ADD_FRIEND = "ADD_FRIEND";
// export const REMOVE_FRIEND = "ADD_FRIEND";
export const ADD_TO_GROUP = "ADD_TO_GROUP";
export const REMOVE_FROM_GROUP = "REMOVE_FROM_GROUP";
export const CLEAR_GROUP = "CLEAR_GROUP";
export const UPDATE_GROUP_QUANTITY = "UPDATE_GROUP_QUANTITY";
// export const TOGGLE_CART = "TOGGLE_CART";

export const FIND_FRIEND = "FIND_FRIEND";
// export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
